# Generated by Django 3.0.3 on 2020-03-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='books',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='books',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='books',
            name='isbn13',
        ),
        migrations.RemoveField(
            model_name='books',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='books',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='books',
            name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='books',
            name='text_reviews_count',
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
